LDLIBS=-lglut -lGLEW -lGL

LDFLAGS += -dylib_file \
/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:\
/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib \
-framework Cocoa -framework OpenGL

all: triangle
clean:
	rm -f *.o triangle
.PHONY: all clean
